/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calcprog.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

double *
calcavg_1(clientData1 *argp, CLIENT *clnt)
{
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, calcAvg,
		(xdrproc_t) xdr_clientData1, (caddr_t) argp,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

returnData2 *
calcmaxmin_1(clientData2 *argp, CLIENT *clnt)
{
	static returnData2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, calcMaxMin,
		(xdrproc_t) xdr_clientData2, (caddr_t) argp,
		(xdrproc_t) xdr_returnData2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

returnData3 *
calcmult_1(clientData3 *argp, CLIENT *clnt)
{
	static returnData3 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, calcMult,
		(xdrproc_t) xdr_clientData3, (caddr_t) argp,
		(xdrproc_t) xdr_returnData3, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
