/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcprog.h"

double *
calcavg_1_svc(clientData1 *argp, struct svc_req *rqstp)
{
	static double  result;
	int i;
	double sum = 0;

	for(i=0; i<argp->N; i++)
		sum = sum + argp->array[i];

	result = (sum / (double)argp->N);
	return &result;
}

returnData2 *
calcmaxmin_1_svc(clientData2 *argp, struct svc_req *rqstp)
{
	static returnData2  result;
	int i;
	int min = argp->array[0];
	int max = argp->array[0];

	for(i=0; i<argp->N; i++)
	{
		if(argp->array[i] > max)
			max = argp->array[i];
		if(argp->array[i] < min)
			min = argp->array[i];
	}
	result.maxmin[0] = max;
	result.maxmin[1] = min;
	return &result;
}

returnData3 *
calcmult_1_svc(clientData3 *argp, struct svc_req *rqstp)
{
	static returnData3  result;
	int i;
	
	for(i=0; i<argp->N; i++)
		result.returnArray[i] = (argp->a * (double)argp->array[i]);

	return &result;
}
