/* 
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCPROG_H_RPCGEN
#define _CALCPROG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct clientData1 {
	int N;
	int array[100];
};
typedef struct clientData1 clientData1;

struct clientData2 {
	int N;
	int array[100];
};
typedef struct clientData2 clientData2;

struct clientData3 {
	double a;
	int array[100];
	int N;
};
typedef struct clientData3 clientData3;

struct returnData2 {
	int maxmin[2];
};
typedef struct returnData2 returnData2;

struct returnData3 {
	double returnArray[100];
};
typedef struct returnData3 returnData3;

#define CALC_PROG 0x23451111
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define calcAvg 1
extern  double * calcavg_1(clientData1 *, CLIENT *);
extern  double * calcavg_1_svc(clientData1 *, struct svc_req *);
#define calcMaxMin 2
extern  returnData2 * calcmaxmin_1(clientData2 *, CLIENT *);
extern  returnData2 * calcmaxmin_1_svc(clientData2 *, struct svc_req *);
#define calcMult 3
extern  returnData3 * calcmult_1(clientData3 *, CLIENT *);
extern  returnData3 * calcmult_1_svc(clientData3 *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calcAvg 1
extern  double * calcavg_1();
extern  double * calcavg_1_svc();
#define calcMaxMin 2
extern  returnData2 * calcmaxmin_1();
extern  returnData2 * calcmaxmin_1_svc();
#define calcMult 3
extern  returnData3 * calcmult_1();
extern  returnData3 * calcmult_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_clientData1 (XDR *, clientData1*);
extern  bool_t xdr_clientData2 (XDR *, clientData2*);
extern  bool_t xdr_clientData3 (XDR *, clientData3*);
extern  bool_t xdr_returnData2 (XDR *, returnData2*);
extern  bool_t xdr_returnData3 (XDR *, returnData3*);

#else /* K&R C */
extern bool_t xdr_clientData1 ();
extern bool_t xdr_clientData2 ();
extern bool_t xdr_clientData3 ();
extern bool_t xdr_returnData2 ();
extern bool_t xdr_returnData3 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCPROG_H_RPCGEN */
